/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AnalysisStatus = IDL.Variant({
  'pending' : IDL.Null,
  'complete' : IDL.Null,
});
export const RoomLabel = IDL.Record({
  'x' : IDL.Int,
  'y' : IDL.Int,
  'direction' : IDL.Text,
  'room' : IDL.Text,
});
export const ScoreBreakdown = IDL.Record({
  'energyBalance' : IDL.Nat,
  'bedrooms' : IDL.Nat,
  'kitchen' : IDL.Nat,
  'entrance' : IDL.Nat,
  'toilets' : IDL.Nat,
});
export const AnalysisRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : AnalysisStatus,
  'roomLabels' : IDL.Vec(RoomLabel),
  'scoreBreakdown' : ScoreBreakdown,
  'floorPlanImage' : IDL.Opt(ExternalBlob),
  'userId' : IDL.Principal,
  'structuralChanges' : IDL.Vec(IDL.Text),
  'floorPlanName' : IDL.Text,
  'issues' : IDL.Vec(IDL.Text),
  'easyFixes' : IDL.Vec(IDL.Text),
  'vastuScore' : IDL.Nat,
  'uploadedAt' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnalysis' : IDL.Func(
      [IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Text],
      [],
    ),
  'deleteAnalysis' : IDL.Func([IDL.Text], [], []),
  'getAllAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
  'getAnalysis' : IDL.Func([IDL.Text], [AnalysisRecord], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAnalysis' : IDL.Func([IDL.Text, AnalysisRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AnalysisStatus = IDL.Variant({
    'pending' : IDL.Null,
    'complete' : IDL.Null,
  });
  const RoomLabel = IDL.Record({
    'x' : IDL.Int,
    'y' : IDL.Int,
    'direction' : IDL.Text,
    'room' : IDL.Text,
  });
  const ScoreBreakdown = IDL.Record({
    'energyBalance' : IDL.Nat,
    'bedrooms' : IDL.Nat,
    'kitchen' : IDL.Nat,
    'entrance' : IDL.Nat,
    'toilets' : IDL.Nat,
  });
  const AnalysisRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : AnalysisStatus,
    'roomLabels' : IDL.Vec(RoomLabel),
    'scoreBreakdown' : ScoreBreakdown,
    'floorPlanImage' : IDL.Opt(ExternalBlob),
    'userId' : IDL.Principal,
    'structuralChanges' : IDL.Vec(IDL.Text),
    'floorPlanName' : IDL.Text,
    'issues' : IDL.Vec(IDL.Text),
    'easyFixes' : IDL.Vec(IDL.Text),
    'vastuScore' : IDL.Nat,
    'uploadedAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnalysis' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Text],
        [],
      ),
    'deleteAnalysis' : IDL.Func([IDL.Text], [], []),
    'getAllAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
    'getAnalysis' : IDL.Func([IDL.Text], [AnalysisRecord], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserAnalyses' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAnalysis' : IDL.Func([IDL.Text, AnalysisRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };